### PR TITLE
fix: zero-copy doesn't work in this architecture

### PR DESCRIPTION
**Pull request by BurntSushi**
... so we used owned values everywhere instead.

### CODE REVIEW

**Review by lucabol — COMMENTED** [review]
This is how I had coded it originally. In this model, wouldn't every Trade contain pointers to heap allocated Strings with copies of the characters that were read originally from the file? My goal is not to heap allocate anything after I have read the whole content of the file in memory at startup.

If this is what is happening here, I am going to take a deeper look tomorrow. Thanks anyhow for your help.

**Comment by BurntSushi** [comment]
> My goal is not to heap allocate anything after I have read the whole content of the file in memory at startup.

What you're asking to do doesn't really make sense. Your program never specifically reads the entire file into memory at startup. The CSV reader _streams_ the contents of the file, and as each record is processed, a `Trade` is created from each of those records. That `Trade` _copies_ the data from the parsed CSV record and creates a new `String` heap allocation. Avoiding this copy, in your current architecture, doesn't really make any sense. If you didn't create a new heap allocation, then where is the data stored? In the record. But that record's memory is reused to parse the next record. So then it would be overwritten. Rust is preventing you from committing this bug.

If you say, "okay maybe my current architecture is bad, how can I change it to do what I want?" Even then, the answer is, you can't. CSV parsing requires unescaping quotes and what not, so if you're using a general purpose CSV parser, it has to do some kind of copying to handle that in the general case, even if your specific data doesn't have quotes or escaped characters. Because of that, there is no architecture that is zero copy so long as you're building on top of the `csv` (and `csv-core`) crates.

What Serde permits is a _zero alloc_ architecture. This is where you can deserialize into things like `&str`, like you had originally. But this is prevented in your current architecture for the reasons I said above. The only way to achieve zero alloc is to process the records as a stream. This is fundamentally incompatible with your stated goal of "reading everything into memory up front."

**Comment by lucabol** [comment]
This is crystal clear. Thanks for taking the time to give such a good explanation. I had not considered the escaping of " inside a csv field, which makes what I am proposing unfeasable.

Am I correct in stating that if it weren't for that single case (i.e. transforming "" into "), then it would theoretically be possible to implement z true zero-copy architecture? I don't see any other 'edge' case in https://tools.ietf.org/html/rfc4180 but I am not an expert.

**Comment by BurntSushi** [comment]
Yes. But you'd have to use memory maps. Or otherwise consider the initial copy from the `read` syscall as not part of the "zero" copy technique. Because if you're using `read`, you have to copy those bytes to heap somewhere, and they have to stay there until you're dong using any data structures derived from that data.

**Comment by lucabol** [comment]
Understood.  It is zero-copy from a memory buffer (wherever it is). Rust would make sure you don't let go of the buffer before you are done with it. An interesting model if your data obliges, but not having escapes.

In any case, I am closing this as it is not an issue with the library and I now understand how things work. Thanks again for your help.

**Pull request closed without merging**
